---
collections_dir: collections
collections:
  adventures:
    output: false
    sort_by: campaign_index
  campaigns:
    output: false
    sort_by: slug
  characters:
    output: false
    sort_by: slug
  locations:
    output: false
    sort_by: slug
  organizations:
    output: false
    sort_by: slug
  settings:
    output: false
    sort_by: name
defaults:
- scope:
    path: ''
    type: 'pages'
  values:
    encoding: 'utf-8'
    layout: 'page'
    title: 'Incunabulum'
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - Rakefile
markdown: kramdown
